spring:
  profiles:
    active: dev
  application:
    name: spring-boot-mvc
  datasource:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springbootmvc?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8

